font=JetBrainsMono Nerd Font:weight=bold:size=12
icons-enabled=yes
anchor=top
prompt="-> "
icon-theme=Adwaita

# sizes
width=50
lines=5
horizontal-pad=5
vertical-pad=1
inner-pad=5

[colors]
background=101a28ff
selection=0b3c56cc
text-color=d9f0fcff
text=d9f0fcff
selection-text=d9f0fcff
selection-match=23ce67ff
match=2389ceff
prompt=33c682ff
input=d9f0fcff

[border]
width=0
radius=0
selection-radius=10
